Add support for PaperMC's new Adventure API Component
dmulloy2/ProtocolLib pull request #1103
Opened 2021-02-25 14:37 UTC by LOOHP

Currently when trying to deepClone chat packets with a non-null `net.kyori.adventure.text.Component` field, an error saying no suitable cloner is found will be thrown.

This PR adds support to that.

2021-02-25 19:36 UTC, dmulloy2 requested changes

2021-02-25 19:36 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/reflect/cloning/BukkitCloner.java
> +import net.kyori.adventure.text.Component;
This import will likely cause issues on non-Paper servers

2021-02-25 19:36 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/AdventureComponentConverter.java
> + * @author LOOHP
I appreciate the documentation, but this looks like the code from https://github.com/PaperMC/Paper/issues/5220#issuecomment-783363243 so I'd probably remove the author tag

2021-02-25 19:36 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/reflect/cloning/BukkitCloner.java
> +					AdventureComponentConverter.clone((Component) source));
Realistically you don't need to cast to Component here, you could just change the clone method below to accept objects

2021-02-25 19:36 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/AdventureComponentConverter.java
> +  	public static Component clone(Component component) {
i.e. `clone(Object component)` and do the cast below (or just have it return Object as well)

2021-02-25 19:36 UTC, dmulloy2 commented
Thanks for the PR! Left a few minor comments before it gets merged

2021-02-26 06:55 UTC, LOOHP commented
I've tested the new commit on both Paper and Spigot and it appears to be working

2021-02-26 06:59 UTC, LOOHP commented
I've tested the new commit on both Paper and Spigot and it appears to be working

2021-02-26 07:22 UTC, LOOHP commented
Emm.. 
`https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom 522 Origin Connection Time-out`
Seems like the repository timed-out causing the build to fail

2021-02-26 21:50 UTC, kashike requested changes

2021-02-26 21:50 UTC, kashike commented on pom.xml
> +			<version>4.5.0</version>
```suggestion
			<version>4.5.1</version>
```

2021-02-26 21:50 UTC, kashike commented on src/main/java/com/comphenix/protocol/wrappers/AdventureComponentConverter.java
> +		return gson.deserialize(gson.serialize((Component) component));
```suggestion
		return (Component) component;
```
Immutable, no need to do this at all.

2021-02-27 11:16 UTC, kashike approved these changes
The *logic* looks good to me.

2021-02-27 19:15 UTC, dmulloy2 approved these changes

2021-02-27 19:15 UTC, merged