fix StreamSerializer compatible(#1813)
dmulloy2/ProtocolLib pull request #1868
Opened 2022-08-23 09:23 UTC by caoli5288

2022-08-23 18:35 UTC, derklaro approved these changes
See #1866 for some discussion about this :)

2022-08-24 00:52 UTC, dmulloy2 requested changes
would love to see a unit test covering this change

2022-08-24 07:32 UTC, caoli5288 commented
> would love to see a unit test covering this change

There are already unit tests covering its functionality and it only fixes the compatibility with 4.x. 

I don't think there is a need to add a new unit test for compatibility.

2022-10-16 18:34 UTC, dmulloy2 approved these changes

2022-10-16 18:37 UTC, merged