Update to 1.19.3
dmulloy2/ProtocolLib pull request #1946
Opened 2022-10-19 14:24 UTC by derklaro

https://www.minecraft.net/en-us/article/minecraft-snapshot-22w42a

2022-11-25 20:15 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java
> +	 * TODO: is this a good idea?
it's probably fine since it's a snapshot API which is obviously subject to change

2022-11-25 20:15 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/events/AbstractStructure.java
> +                Converters.collection(
love this

2022-11-25 20:17 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/PlayerInfoData.java
> +								 null); // TODO: do we want to support this?
typically i'll do it if it's easy, otherwise i'll wait until someone requests it

2022-12-10 00:14 UTC, LOOHP commented
I know this is just a draft and is incomplete, but just incase this is not known, a errors seems to occur when listening to entity metadata packets on 1.19.3
```
java.lang.ClassCastException: class net.minecraft.network.syncher.DataWatcher$Item cannot be cast to class net.minecraft.network.syncher.DataWatcher$b (net.minecraft.network.syncher.DataWatcher$Item and net.minecraft.network.syncher.DataWatcher$b are in unnamed module of loader java.net.URLClassLoader @759ebb3d)
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.3.jar:git-Paper-310]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.3.jar:git-Paper-310]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.loohp.bookshelf.listeners.PacketListenerEvents$1.write(PacketListenerEvents.java:144) ~[Bookshelf-3.1.1.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:428) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:08:00 INFO]: LOOHP lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class net.minecraft.network.syncher.DataWatcher$Item cannot be cast to class net.minecraft.network.syncher.DataWatcher$b (net.minecraft.network.syncher.DataWatcher$Item and net.minecraft.network.syncher.DataWatcher$b are in unnamed module of loader java.net.URLClassLoader @759ebb3d)
```

2022-12-10 12:04 UTC, derklaro commented
@LOOHP these items are now wrapped in a "DataValue", there is a new wrapper class to represent that type

2022-12-10 17:01 UTC, LOOHP commented
> @LOOHP these items are now wrapped in a "DataValue", there is a new wrapper class to represent that type

Oh I see, thanks for the heads up. May I suggest a method to get data values from a `WrappedDataWatcher` similar to `getWatchableObjects()`? It would be convenient without having to write our own.

2022-12-11 15:13 UTC, derklaro commented
@LOOHP we could, but the thing is that there is no direct connection between a DataWatcher and the DataValue (or, in other words, there is no field or getter method which gives us all values from a watcher - which means that we need to convert all values manually). Will take a look if adding that method is helpful and do it later/tomorrow 👍

2022-12-13 15:57 UTC, dmulloy2 requested changes

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java
> -				if (!MINECRAFT_FULL_PACKAGE.startsWith(MINECRAFT_PREFIX_PACKAGE)) {
this was added somewhat recently to fix issues with forge servers. merge conflict, or does this cause an issue in 1.19.3?

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java
> -			return getMinecraftClass("world.entity.Entity", "Entity");
here as well

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java
> -		return getMinecraftClass("world.effect.MobEffectList", "MobEffectList", "world.effect.MobEffect");
and here

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java
> +			// todo: we can also use getField(0).getGenericType().getTypeParameters()[0]; but this should hold for now
not blocking, but is there anything else we can use to identify these classes? wondering if we could iterate through the classes and apply some test

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java
> +	public static final MinecraftVersion FEATURE_PREVIEW_UPDATE = new MinecraftVersion("1.19.3");
is this the official name or just a placeholder while it was in snapshot?

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/WrappedParticle.java
> +import org.joml.Vector3f;
not a blocker for a 1.19.3 snapshot build, but this will probably cause an import exception on older versions

2022-12-13 15:57 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/wrappers/WrappedParticle.java
> +		if (MinecraftVersion.FEATURE_PREVIEW_UPDATE.atOrAbove()) {
there's probably a fuzzy class contract that could cover these 2 implementations of vector3f

2022-12-14 01:39 UTC, dmulloy2 commented
megred in eebb99fa37a196a40b1c38a90a1f4a02f83d4b59

2022-12-14 01:39 UTC, closed without merging