Update bytebuddy, add tab completion for PacketLogging command and use cache for getFieldAccessor
dmulloy2/ProtocolLib pull request #1982
Opened 2022-11-13 22:53 UTC by camdenorrb

- ByteBuddy seemed to be out of date so I updated it
- Packet logging command seemed a bit complex, so I added tab completion to make it easier to use
- `getFieldAccessor` seemed a bit slow on our production servers so I went ahead and added a cache for it.

2022-11-14 07:34 UTC, derklaro reviewed
I think the packet logging tab complete *might* be reasonable, but the field accessor cache is not. It would be much better to find the places where field accessors are requested and update the code to use fields for them, rather than caching them in a map.

2022-11-14 10:05 UTC, camdenorrb commented
@derklaro it was just a quick fix while keeping to pattern

2022-11-25 20:11 UTC, dmulloy2 requested changes

2022-11-25 20:11 UTC, dmulloy2 commented on src/main/resources/plugin.yml
> +authors: [dmulloy2, comphenix, camdenorrb]
no

2022-11-25 20:11 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/PacketLogging.java
> +	public List<String> onTabComplete(@NotNull final CommandSender commandSender, @NotNull final Command command, @NotNull final String s, @NotNull final String[] strings) {
looks good

2022-11-25 20:11 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/collections/ExpireHashMap.java
> +	private final PriorityBlockingQueue<ExpireEntry> expireQueue =  new PriorityBlockingQueue<>();
reason behind this change?

2022-11-25 20:11 UTC, dmulloy2 commented on src/main/java/com/comphenix/protocol/reflect/accessors/MethodHandleHelper.java
> +
would prefer if the caching stuff was in a separate PR

2022-11-25 20:11 UTC, dmulloy2 commented on pom.xml
> +			<version>1.12.18</version>
any known changes caused by this?

2022-11-25 20:13 UTC, closed without merging